x1 = float(input("x1="))
y1 = float(input("y1="))
x2 = float(input("x2="))
y2 = float(input("y2="))
x3 = float(input("x3="))
y3 = float(input("y3="))
x4 = float(input("x4="))
y4 = float(input("y4="))
x = min(x1, x3)    # нужно добавить все х и у если убрать условие про левій нижний и правій верхний, а заменить просто на противоположные
y = min(y1, y3)
z = max(x2, x4)
t = max(y2, y4)
print("( ", x, " ; ", y, " )")
print("( ", z, " ; ", t, " )")